#!/bin/sh
# Action entrypoint: Claude やユーザーがプラグインの置き場所を知らなくても
# show.sh を呼べるよう、herdr が公開する安定パス（plugin config dir）に薄い
# シム `show` を書き出す。which-key プラグインと同じ方式。
# 呼び出し: herdr plugin action invoke mado.agent-report-viewer.install-cli
set -eu

root=${HERDR_PLUGIN_ROOT:-$(cd "$(dirname "$0")" && pwd)}
cfg=${HERDR_PLUGIN_CONFIG_DIR:-}
if [ -z "$cfg" ]; then
	echo "install-cli: HERDR_PLUGIN_CONFIG_DIR is not set (run via herdr plugin action invoke)" >&2
	exit 1
fi
state=${HERDR_PLUGIN_STATE_DIR:-}
herdr=${HERDR_BIN_PATH:-herdr}

mkdir -p "$cfg"
shim="$cfg/show"
# シムには絶対パスを焼き込む。show.sh はフックと同じ state dir を見ないと
# ペインを共有できないので、state dir も一緒に渡す。
cat > "$shim" <<EOF
#!/bin/sh
# generated by mado.agent-report-viewer install-cli — edit the plugin, not this file
HERDR_PLUGIN_STATE_DIR='$state' HERDR_BIN_PATH='$herdr' exec sh '$root/show.sh' "\$@"
EOF
chmod +x "$shim"

printf 'agent-report-viewer: wrote %s\n\n' "$shim"
printf 'Show markdown in the report pane, from any pane in this herdr:\n\n'
printf '  sh "$(herdr plugin config-dir mado.agent-report-viewer)/show" docs/plan.md\n'
